import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "よわよわエンジニアの日記",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <header>Header</header>

        {children}

        <footer>Footer</footer>
      </body>
    </html>
  );
}
